### ISSUE TITLE
When should we display the "Explanation" and the video and or other links?

### ISSUE THREAD

**Issue by grahamp** [pokadmin/kq_app#26]
When and how do we display the Explanation and video links?
Is there a "show me the answer" button?
Do we show it after several failures?
When the user get the right answer? All of the above?

**Comment by NickD7802** [comment]
Two options: Tutor mode and Quiz Mode. Click the links below to see examples from a multiple choice question web app.

Tutor Mode: [](https://drive.google.com/file/d/16zWxgD5RBdJ60HqtQms0pSHkHPHvqtmK/view?usp=sharing)
Quiz Mode:  [](https://drive.google.com/file/d/1P7nlMR1ExyGi3PGfKCaFdlC7NtfMBmLt/view?usp=sharing)

I think tutor mode may be most easy for both coders and users but open to feedback.

**Comment by NickD7802** [comment]
I think sticking to Quiz mode as described in the original specs by Tarun will be easiest. I think most are preferring Quiz mode anyway. I edited the wireframe PPT to reflect the original specs with UIs 1-3.

[Slides](https://docs.google.com/presentation/d/1KjU5AtWNBEsaHVvGYu5ZlhUPCmQ7HcYfOzykebxeKIo/edit?usp=sharing
)
My suggestions for the following:
1. When and how do we display the Explanation and video links?**--Explanation and links should be on it's own separate page (see slide 3). To access this page, one will need to hit the "end quiz" button which will become enabled after 20 questions are completed.**

2. Is there a "show me the answer" button?-- **I think this can be built into the dialogue box (see slide 2) e.g after clicking the answer you will get the following: "Correct! Your score is 1/n. <OR> Incorrect! The Answer is B. Your Score is 1/n"**

3. Do we show it after several failures?---**I would only give the person one chance.**

4. When the user get the right answer? All of the above? --- **would tell them with the dialogue box whether it is right or wrong and if wrong what the correct answer is.**

**Comment by grahamp** [comment]
> Two options: Tutor mode and Quiz Mode. Click the links below to see examples from a multiple choice question web app.
> 
> [Tutor Mode](https://drive.google.com/file/d/16zWxgD5RBdJ60HqtQms0pSHkHPHvqtmK/view?usp=sharing) [Quiz Mode](https://drive.google.com/file/d/1P7nlMR1ExyGi3PGfKCaFdlC7NtfMBmLt/view?usp=sharing)
> 
> I think tutor mode may be most easy for both coders and users but open to feedback.

I like tutor mode.

**Comment by grahamp** [comment]
@NickD7802 Great job!  I am closing this as done. If I missed something just re-open with a comment.
